version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing Node.js dependencies...

  build:
    commands:
      - echo Build started on AWS CodeBuild
      - npm install
      - echo Build completed successfully

artifacts:
  files:
    - '**/*'